# Config file for automatic testing at travis-ci.org

language: python

install:
  - pip install tox
  - python setup.py -q install
  - pip install -r requirements-test.txt

script:
  - tox

env:
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py32-django15
  - TOXENV=py32-django16
  - TOXENV=py32-django17
  - TOXENV=py32-django18
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django15
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18

after_success: coveralls
